# Generated by Django 5.1.7 on 2025-03-09 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('oil_change', 'Oil Change'), ('brake_inspection', 'Brake Inspection'), ('tire_rotation', 'Tire Rotation')], max_length=50)),
                ('description', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='vehicle.vehicle')),
            ],
        ),
    ]
